#!/bin/bash

# Delete the Twitch certificates from the certificate store.
while true; do
	SHA=$(security find-certificate -c "Twitch Developer Rig" -Z 2> /dev/null | grep -F SHA-1 | sed 's/.* //')
	[ -n "$SHA" ] || break
	sudo security delete-certificate -Z "$SHA"
done

# If Firefox is installed, undo all changes.
FF=/Applications/Firefox.app/Contents/Resources
if [ -d $FF ]; then
	rm -f $FF/defaults/pref/twitch-developer-rig.js
	sed -e '/Twitch Developer Rig CA certificate addition/,$d' -i "" $FF/mozilla.cfg
fi
